name: CI

# on = this event
# whenever theeres a push
on: [push]

# stuff that will happen
jobs:
  # we will do SAST testing
  # bandit is a SAST pythin tool
  
  # define a job
  sast_scan:

    name: Run Bandit Scan
    
    # specify platform to run on
    runs-on: ubuntu-latest

    # stuff that will happen
    steps:


    # name of something that will happen
    - name: checkout code
    # action for this name
      uses: actions/checkout@v2


    
    # name of something that will happen
    - name: setup python
    # action for this name
      uses: actions/setup-python@v2
      with:
        python-version: 3.8


    # name of something that will happen
    - name: install bandit

      # run - runs command on ubuntu machine
      run: pip install bandit

    - name: run bandit scan
      # scan files for SAST
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: upload artifact
      uses: actions/upload-artifact@v3
      # always execute below 
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json

  image_scan:
      name: build and test
      runs-on: ubuntu-latest

      steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup docker
      # actions that setup docker
        uses: docker-practice/actions-setup-docker@v1 
        with: 
          docker_version: '20.10.7'

      - name: build image 
        run: docker build -f Dockerfile -t myapp:latest .

      - name: scan image for sec issues

        # pipe is multiline command 
        run: |
          curl -fssL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          docker scout quickview
          docker scout cves
      

        

    
     


  
      
      
